version: "3"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - sqlite-volume:/app/db
    depends_on:
      - g4f

  sqlite_web:
    container_name: sqlite_web
    restart: always
    ports:
      - "8080:8080"
    build:
      context: "."
      dockerfile: DockerfileSqlite
    volumes:
      - sqlite-volume:/data
    env_file:
      - src/config/config.env

  g4f:
    container_name: g4f
    restart: always
    image: hlohaus789/g4f:latest
    ports:
      - "8081:8080"
      - "1337:1337"
      - "7900:7900"
    shm_size: 512m

volumes:
  sqlite-volume:
