version: "3"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py -d=sqlite
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - sqlite-volume:/code/db
    depends_on:
      - flask_app

  sqlite_web:
    container_name: sqlite_web
    restart: always
    ports:
      - "8080:8080"
    build:
      context: "."
      dockerfile: DockerfileSqlite
    volumes:
      - sqlite-volume:/data
    env_file:
      - config/config.env

  flask_app:
    container_name: flask_app
    restart: always
    build:
      context: "."
      dockerfile: DockerfileFlask
    ports:
      - "1337:1337"

volumes:
  sqlite-volume:
